var data = [
  {
    bib: 1231,
    rank: 1,
    name: 'Teszt Elek',
    sex: 'M',
    category: 'E',
    age: 30,
    birth: '1987-03-03',
    city: 'Gödöllő',
    team: 'AWS',
    nationality: 'HUN',
    formattedResult: '1:13:30',
    result: 73.5
  },
  {
    bib: 3211,
    rank: 2,
    name: 'Teszt Elemer',
    sex: 'M',
    category: 'C',
    age: 29,
    birth: '1988-03-03',
    city: 'Budapest',
    team: '',
    nationality: 'HUN',
    formattedResult: '1:16:45',
    result: 73.75
  },
  {
    bib: 1292,
    rank: 3,
    name: 'Hutníková Magda',
    sex: 'F',
    category: 'E',
    age: 25,
    birth: '1992-03-03',
    city: 'Eger',
    team: '',
    nationality: 'SVK',
    formattedResult: '1:19:15',
    result: 79.25
  },
  {
    bib: 3219,
    rank: 4,
    name: 'Teszt Elemer',
    sex: 'M',
    category: 'O',
    age: 29,
    birth: '1988-03-03',
    city: 'Budapest',
    team: 'AWS',
    nationality: 'HUN',
    formattedResult: '1:25:15',
    result: 85.25
  },
  {
    bib: 1219,
    rank: 5,
    name: 'Teszt Elemeria',
    sex: 'F',
    category: 'O',
    age: 31,
    birth: '1985-03-03',
    city: 'Budapest',
    team: 'BWS',
    nationality: 'HUN',
    formattedResult: '1:26:30',
    result: 86.5
  },
  {
    bib: 3318,
    name: 'Teszt Ele',
    sex: 'M',
    category: 'O',
    age: 31,
    birth: '1985-03-03',
    city: 'Budapest',
    team: '',
    nationality: 'HUN',
    formattedResult: 'DNF',
    result: 0
  },
  {
    bib: 3319,
    name: 'Teszt Alma 2',
    sex: 'F',
    category: 'O',
    age: 21,
    birth: '1995-03-03',
    city: 'Budapest',
    team: '',
    nationality: 'HUN',
    formattedResult: 'DQ',
    result: 0
  },
  {
    bib: 3119,
    name: 'Teszt Elemer 2',
    sex: 'M',
    category: 'O',
    age: 21,
    birth: '1995-03-03',
    city: 'Budapest',
    team: '',
    nationality: 'HUN',
    formattedResult: 'DQ',
    result: 0
  },
  {
    bib: 3321,
    name: 'Teszt Alma 3',
    sex: 'F',
    category: 'O',
    age: 34,
    birth: '1981-03-03',
    city: 'Budapest',
    team: '',
    nationality: 'HUN',
    formattedResult: 'DNS',
    result: 0
  }
];
